### ISSUE TITLE
Cookiebot GDPR compliance

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#100]
### Please select the priority level by adding one of the following labels to this issue?

Priority-2 (High e.g. Core functionality is not working)

### Describe the bug and the expected behaviour.

We received an email from Cookiebot today explaining that the way we collect cookies might not be GDPR compliant, as cookies are being collected before people consent. Email attached below.

### Screenshots or a link to a Loom Recording

[Cookie scan report October 2023.pdf](https://github.com/yalla-coop/shannon-trust-website/files/12846617/Cookie.scan.report.October.2023.pdf)

### What browsers are you seeing the problem on?

Other

**Comment by cyberteenie** [comment]
Thanks @ShannonTrust - we are looking into this!

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, no need to apologise, we completely understand. Thank you for the update though.

**Comment by redahaq** [comment]
Hi @ShannonTrust, thank you so much for your patience. This should be fixed now - I'm running a Cookiebot scan so you may get a report in the next 24hrs or so, just FYI.

**Comment by cyberteenie** [comment]
@ShannonTrust - let us know if the report looks good and we can close this issue!

**Comment by ShannonTrust** [comment]
Thanks, @redahaq and @cyberteenie. No issues were flagged on the new report. Thanks for sorting.

**Comment by ShannonTrust** [comment]
@cyberteenie - this issue seems to have come up again on our most recent report, can you look into it again, please?

[Cookie scan report December 2023.pdf](https://github.com/yalla-coop/shannon-trust-website/files/13701648/Cookie.scan.report.December.2023.pdf)

**Comment by cyberteenie** [comment]
@ShannonTrust - I think this may actually be due to Google Analytics, but let me speak to Ramy and get back to you on this!

**Comment by redahaq** [comment]
Hi @ShannonTrust, cc @cyberteenie; so the reason this issue came up again was due to the embedded YouYube video on the Big Give Christmas Challenge story - the YouTube cookies have now been classified and prior consent is required before displaying the embedded video.

I've reviewed the lastest Cookiebot scan report, and there doesn't seem to be a a prior consent issue any more but please let me know if any issues have come up in Jan's report, as you are emailed a more detailed report than what is available by logging in to Cookiebot. If all is clear we can close the issue.

For future YouTube embedded videos, we'd recommend ticking the 'Enable enhanced privacy mode' checkbox. This prevents the tracking cookies being added. 

<img width="423" alt="Screenshot 2024-01-12 at 03 29 21" src="https://github.com/yalla-coop/shannon-trust-website/assets/39345463/4ccbfe23-6109-4be7-a079-c8b0bf4b59e1">

**Comment by ShannonTrust** [comment]
Thanks, @redahaq. That's really useful to know. Nothing was flagged in our latest report, so thanks for looking into this.
