### ISSUE TITLE
MailChimp authentication

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#112]
### Is your feature / client request related to a problem? Please describe.

We received an email from MailChimp regarding email requirements changing and we need to authenticate our domain. We need to create CNAME and DMARC records in our domain provider, so when our website has switched over, could you look at this for us, please?

### Screenshots or a link to a Loom Recording

[🍨 The inside scoop on new email requirements from Google and Yahoo.pdf](https://github.com/yalla-coop/shannon-trust-website/files/14138329/The.inside.scoop.on.new.email.requirements.from.Google.and.Yahoo.pdf)

**Comment by cyberteenie** [comment]
Hey @ShannonTrust - will have a look thanks!

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
this issue seems to be fixed by editing the DNS records and Mailchimp settings, not sure if its better to communicate the IT team who manage the domain settings? and tbh I don't have the experience in this area.
i tried to log into Mailchimp but there is a 2FA.
let me know if the there is no other way to fix this, so I can do some research and look further into it
hope that makes sense

**Comment by ShannonTrust** [comment]
Thanks @RamyAlshurafa. I've spoken to our technology manager and he should be able to sort it out once the website domain has switched over. I'll let you know if we need your support any further.

**Comment by cyberteenie** [comment]
Great, I will close this issue for now. Let us know if there is anything else we can do to support.
