### ISSUE TITLE
AXE accessibility audit

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#95]
### Describe the solution you'd like

We'd like a full accessibility audit done to our website based on the latest web content accessibility guidelines. We previously spoke to Joe about this and the process you go through.

- [x] Home page => Add accessible text to the search icon on the header

- [x] All pages => Add lang attribute to every HTML element on the website
- [x] All pages => Make Elements not focusable (at dropdowns on the header i.e. What we do and How you can help)
- [x] All pages => Provides the text label for social media icons

- [x] Work for us => Element must meet minimum color contrast ratio threshold i.e. on Jobs that is going to close soon the white colors (##ffffff) contrast file at the red background (#ff5b59).
Suggestion: Change the red background to (#cc4847) or change the colors to (#050d30)
- [x] Work for us => id attribute value must be unique i.e. employee benefits section | Class:Work-For-Us-S3

- [x] become a coach=> Links must have a discernible text i.e. Logo
- [x] become a coach=> Elements must Only use allowed ARIA attribute i.e. Logo
- [x] become a coach=> ARIA roles used must conform to valid values i.e. Logo
- [x] become a coach=> Interactive controls must not be nested i.e. Logo

- [x] Get started with Turning Pages => Elements must only use allowed ARIA attributes i.e. Logo
- [x] Get started with Turning Pages => Links must have discernible text i.e. digital app YouTube video | Class:.embedly-embed #player 

- [x] Stories => 4 Minor enhancements

- [x] Volunteer => Elements must meet minimum color contrast ratio thresholds i.e. Submit button disabled status (Opacity:50%), it can be fixed it's (Opacity:80%)
- [x] Volunteer => ARIA input fields must have an accessible name
- [x] Volunteer => **(3 Minor)** IDs of an active element must be unique:
    - [x] Form checkboxes (id attribute: checkbox) -> Note for div team: the new id I just added numbers to the checkbox id so the previous id was '#checkbox' and the new id become '#checkbox-{number}' and the number is the checkbox order on the form
    - [x] Form radio buttons (id attribute: Yes/No)-> Note for div team: the new id I just added numbers to the Yes/No id so the previous id was '#Yes' / '#No' and the new id become '#Yes-{number}' / '#No-{number}' and the number is Yes item/No item order on the form
    - [x] Form radio buttons (id attribute: Yes/No)-> Note for div team: the new id I just added numbers to the Yes/No id so the previous id was '#Yes' / '#No' and the new id become '#Yes-{number}' / '#No-{number}' and the number is Yes item/No item order on the form

- [x] News and views => 1 Minor enhancements

- [x] Pre search => Input buttons must have discernible text

**Comment by cyberteenie** [comment]
Ok great! We will slot this into the upcoming month. Thanks!

**Comment by cyberteenie** [comment]
Hi @ShannonTrust -
In order to solve the remaining issues that came up from the accessibility audit, we have a few questions:

1. On the Work with Us page: we have a color contrast issue and to solve this problem we need to change the colors to make the background lighter or the text darker. Are you okay if we tweak the colors to make this work?

2.  On the stories page: we have an issue with Webflow not building the story cards in an accessible way. This means we will have to rebuild the cards ourselves, which would take a maximum of a day of work. As we are currently in surplus, I think that this is fine, but I just wanted to double check and get confirmation from you that we can work on it as it would mean no visible change..it is just structuring the website so that it is more accessible for people who might be using screenreaders to view the page.


Your input would be much appreciated! Thanks!

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, that is absolutely fine, please go ahead with those changes. Thank you

**Comment by cyberteenie** [comment]
Closing this now as those changes are now complete.
